# Generated by Django 4.1.7 on 2023-03-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoplist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Shopping List', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('is_taken', models.BooleanField(default=False)),
                ('shoplist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoplist.shoplist')),
            ],
        ),
    ]
