# Generated by Django 4.1.7 on 2023-03-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0002_remove_item_id_item_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_id',
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
